// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.17.5_@parcel+watcher@2.5.1_@types+node@24.0.3_better-sqlite3@11.10.0_db0@0.3.2_better-_qld5zl4aitworr2yf6botpervm/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@1.14.0_magicast@0.3.5_vite@6.3.5_@types+node@24.0.3_jiti@2.4.2_lightningcss@1.30.1_atuct42rl5gktagg44ygsxs5di/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__site-config__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-site-config@3.2.1_magicast@0.3.5_vue@3.5.17_typescript@5.8.3_/node_modules/nuxt-site-config/dist/runtime/server/routes/__site-config__/debug').default>>>>
    }
    '/robots.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+robots@5.2.11_magicast@0.3.5_vue@3.5.17_typescript@5.8.3_/node_modules/@nuxtjs/robots/dist/runtime/server/routes/robots-txt').default>>>>
    }
    '/__robots__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+robots@5.2.11_magicast@0.3.5_vue@3.5.17_typescript@5.8.3_/node_modules/@nuxtjs/robots/dist/runtime/server/routes/__robots__/debug').default>>>>
    }
    '/__robots__/debug-path.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+robots@5.2.11_magicast@0.3.5_vue@3.5.17_typescript@5.8.3_/node_modules/@nuxtjs/robots/dist/runtime/server/routes/__robots__/debug-path').default>>>>
    }
    '/__sitemap__/nuxt-content-urls.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.1_h3@1.15.3_magicast@0.3.5_vite@6.3.5_@types+node@24.0.3_jiti@2.4.2_light_egquftunqxcf2mw7skatemn34m/node_modules/@nuxtjs/sitemap/dist/runtime/server/routes/__sitemap__/nuxt-content-urls-v3').default>>>>
    }
    '/__sitemap__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.1_h3@1.15.3_magicast@0.3.5_vite@6.3.5_@types+node@24.0.3_jiti@2.4.2_light_egquftunqxcf2mw7skatemn34m/node_modules/@nuxtjs/sitemap/dist/runtime/server/routes/__sitemap__/debug').default>>>>
    }
    '/__sitemap__/style.xsl': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.1_h3@1.15.3_magicast@0.3.5_vite@6.3.5_@types+node@24.0.3_jiti@2.4.2_light_egquftunqxcf2mw7skatemn34m/node_modules/@nuxtjs/sitemap/dist/runtime/server/routes/sitemap.xsl').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.1_h3@1.15.3_magicast@0.3.5_vite@6.3.5_@types+node@24.0.3_jiti@2.4.2_light_egquftunqxcf2mw7skatemn34m/node_modules/@nuxtjs/sitemap/dist/runtime/server/routes/sitemap.xml').default>>>>
    }
    '/__og-image__/font/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@5.1.7_@unhead+vue@2.0.10_vue@3.5.17_typescript@5.8.3___magicast@0.3.5_unstorage_kp7tsigzdcyd2hmwstiwp35fe4/node_modules/nuxt-og-image/dist/runtime/server/routes/font').default>>>>
    }
    '/__og-image__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@5.1.7_@unhead+vue@2.0.10_vue@3.5.17_typescript@5.8.3___magicast@0.3.5_unstorage_kp7tsigzdcyd2hmwstiwp35fe4/node_modules/nuxt-og-image/dist/runtime/server/routes/debug.json').default>>>>
    }
    '/__og-image__/image/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@5.1.7_@unhead+vue@2.0.10_vue@3.5.17_typescript@5.8.3___magicast@0.3.5_unstorage_kp7tsigzdcyd2hmwstiwp35fe4/node_modules/nuxt-og-image/dist/runtime/server/routes/image').default>>>>
    }
    '/__og-image__/static/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@5.1.7_@unhead+vue@2.0.10_vue@3.5.17_typescript@5.8.3___magicast@0.3.5_unstorage_kp7tsigzdcyd2hmwstiwp35fe4/node_modules/nuxt-og-image/dist/runtime/server/routes/image').default>>>>
    }
    '/__schema-org__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-schema-org@5.0.5_@unhead+vue@2.0.10_vue@3.5.17_typescript@5.8.3___magicast@0.3.5_vue@3.5.17_typescript@5.8.3_/node_modules/nuxt-schema-org/dist/runtime/server/routes/__schema-org__/debug').default>>>>
    }
    '/__link-checker__/inspect': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-link-checker@4.3.1_db0@0.3.2_better-sqlite3@11.10.0__ioredis@5.6.1_magicast@0.3.5_vite@6_wy5zcyvf74jv57h6ruoplb7o5a/node_modules/nuxt-link-checker/dist/runtime/server/routes/__link-checker__/inspect').default>>>>
    }
    '/__link-checker__/links': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-link-checker@4.3.1_db0@0.3.2_better-sqlite3@11.10.0__ioredis@5.6.1_magicast@0.3.5_vite@6_wy5zcyvf74jv57h6ruoplb7o5a/node_modules/nuxt-link-checker/dist/runtime/server/routes/__link-checker__/links').default>>>>
    }
    '/__link-checker__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-link-checker@4.3.1_db0@0.3.2_better-sqlite3@11.10.0__ioredis@5.6.1_magicast@0.3.5_vite@6_wy5zcyvf74jv57h6ruoplb7o5a/node_modules/nuxt-link-checker/dist/runtime/server/routes/__link-checker__/debug').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/__nuxt_content/:collection/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.6.0_better-sqlite3@11.10.0_magicast@0.3.5/node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/__nuxt_content/:collection/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.6.0_better-sqlite3@11.10.0_magicast@0.3.5/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
  }
}
export {}