// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.5_@parcel+watcher@2.5.1_@types+node@24.0.3_better-sqlite3@11.10.0_db0@0.3.2_better-_qld5zl4aitworr2yf6botpervm/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.5_@parcel+watcher@2.5.1_@types+node@24.0.3_better-sqlite3@11.10.0_db0@0.3.2_better-_qld5zl4aitworr2yf6botpervm/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.5_@parcel+watcher@2.5.1_@types+node@24.0.3_better-sqlite3@11.10.0_db0@0.3.2_better-_qld5zl4aitworr2yf6botpervm/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-site-config@3.2.1_magicast@0.3.5_vue@3.5.17_typescript@5.8.3_/node_modules/nuxt-site-config/dist/runtime/app/plugins/0.siteConfig.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.5_@parcel+watcher@2.5.1_@types+node@24.0.3_better-sqlite3@11.10.0_db0@0.3.2_better-_qld5zl4aitworr2yf6botpervm/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+content@3.6.0_better-sqlite3@11.10.0_magicast@0.3.5/node_modules/@nuxt/content/dist/runtime/plugins/websocket.dev.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.5_@parcel+watcher@2.5.1_@types+node@24.0.3_better-sqlite3@11.10.0_db0@0.3.2_better-_qld5zl4aitworr2yf6botpervm/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.5_@parcel+watcher@2.5.1_@types+node@24.0.3_better-sqlite3@11.10.0_db0@0.3.2_better-_qld5zl4aitworr2yf6botpervm/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.5_@parcel+watcher@2.5.1_@types+node@24.0.3_better-sqlite3@11.10.0_db0@0.3.2_better-_qld5zl4aitworr2yf6botpervm/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.5_@parcel+watcher@2.5.1_@types+node@24.0.3_better-sqlite3@11.10.0_db0@0.3.2_better-_qld5zl4aitworr2yf6botpervm/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.5_@parcel+watcher@2.5.1_@types+node@24.0.3_better-sqlite3@11.10.0_db0@0.3.2_better-_qld5zl4aitworr2yf6botpervm/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.5_@parcel+watcher@2.5.1_@types+node@24.0.3_better-sqlite3@11.10.0_db0@0.3.2_better-_qld5zl4aitworr2yf6botpervm/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@2.5.0_vite@6.3.5_@types+node@24.0.3_jiti@2.4.2_lightningcss@1.30.1_terser@5.43_xyl3arczwzlhazhk2pjl5kv5z4/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@2.5.0_vite@6.3.5_@types+node@24.0.3_jiti@2.4.2_lightningcss@1.30.1_terser@5.43_xyl3arczwzlhazhk2pjl5kv5z4/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-seo-utils@7.0.12_magicast@0.3.5_rollup@4.44.0_vue@3.5.17_typescript@5.8.3_/node_modules/nuxt-seo-utils/dist/runtime/app/plugins/siteConfig.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-seo-utils@7.0.12_magicast@0.3.5_rollup@4.44.0_vue@3.5.17_typescript@5.8.3_/node_modules/nuxt-seo-utils/dist/runtime/app/plugins/inferSeoMetaPlugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-seo-utils@7.0.12_magicast@0.3.5_rollup@4.44.0_vue@3.5.17_typescript@5.8.3_/node_modules/nuxt-seo-utils/dist/runtime/app/plugins/titles.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-link-checker@4.3.1_db0@0.3.2_better-sqlite3@11.10.0__ioredis@5.6.1_magicast@0.3.5_vite@6_wy5zcyvf74jv57h6ruoplb7o5a/node_modules/nuxt-link-checker/dist/runtime/app/plugins/ui.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-schema-org@5.0.5_@unhead+vue@2.0.10_vue@3.5.17_typescript@5.8.3___magicast@0.3.5_vue@3.5.17_typescript@5.8.3_/node_modules/nuxt-schema-org/dist/runtime/app/plugins/defaults.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-schema-org@5.0.5_@unhead+vue@2.0.10_vue@3.5.17_typescript@5.8.3___magicast@0.3.5_vue@3.5.17_typescript@5.8.3_/node_modules/nuxt-schema-org/dist/runtime/app/plugins/init.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-og-image@5.1.7_@unhead+vue@2.0.10_vue@3.5.17_typescript@5.8.3___magicast@0.3.5_unstorage_kp7tsigzdcyd2hmwstiwp35fe4/node_modules/nuxt-og-image/dist/runtime/app/plugins/og-image-canonical-urls.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-og-image@5.1.7_@unhead+vue@2.0.10_vue@3.5.17_typescript@5.8.3___magicast@0.3.5_unstorage_kp7tsigzdcyd2hmwstiwp35fe4/node_modules/nuxt-og-image/dist/runtime/app/plugins/route-rule-og-image.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+robots@5.2.11_magicast@0.3.5_vue@3.5.17_typescript@5.8.3_/node_modules/@nuxtjs/robots/dist/runtime/app/plugins/robot-meta.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_db0@0.3.2_better-sqlite3@11.10.0__embla-carousel@8.6.0_io_c3rkd63amtmtd64x55vod7vajy/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+icon@1.14.0_magicast@0.3.5_vite@6.3.5_@types+node@24.0.3_jiti@2.4.2_lightningcss@1.30.1_atuct42rl5gktagg44ygsxs5di/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.5_@parcel+watcher@2.5.1_@types+node@24.0.3_better-sqlite3@11.10.0_db0@0.3.2_better-_qld5zl4aitworr2yf6botpervm/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.5_@parcel+watcher@2.5.1_@types+node@24.0.3_better-sqlite3@11.10.0_db0@0.3.2_better-_qld5zl4aitworr2yf6botpervm/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")> &
  InjectionType<typeof import("../../plugins/color-mode.client")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.5_@parcel+watcher@2.5.1_@types+node@24.0.3_better-sqlite3@11.10.0_db0@0.3.2_better-_qld5zl4aitworr2yf6botpervm/node_modules/nuxt/dist/pages/runtime/plugins/prerender.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-seo-utils@7.0.12_magicast@0.3.5_rollup@4.44.0_vue@3.5.17_typescript@5.8.3_/node_modules/nuxt-seo-utils/dist/runtime/app/plugins/1.absoluteImageUrls.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-seo-utils@7.0.12_magicast@0.3.5_rollup@4.44.0_vue@3.5.17_typescript@5.8.3_/node_modules/nuxt-seo-utils/dist/runtime/app/plugins/0.routeRules.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-seo-utils@7.0.12_magicast@0.3.5_rollup@4.44.0_vue@3.5.17_typescript@5.8.3_/node_modules/nuxt-seo-utils/dist/runtime/app/plugins/defaults.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt-site-config:init' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'nuxt-seo:fallback-titles' | 'nuxt-schema-org:defaults' | 'nuxt-schema-org:init' | '@nuxt/icon' | 'nuxt:checkIfLayoutUsed' | 'nuxt-seo:defaults'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
