// Generated by nuxt-schema-org

declare module '@nuxt/schema' {
  export interface RuntimeNuxtHooks {
    'schema-org:meta': (meta: import('../../node_modules/.pnpm/nuxt-schema-org@5.0.5_@unhead+vue@2.0.10_vue@3.5.17_typescript@5.8.3___magicast@0.3.5_vue@3.5.17_typescript@5.8.3_/node_modules/nuxt-schema-org/dist/runtime/types').MetaInput) => void | Promise<void>
  }
}
declare module '#app' {
  export interface RuntimeNuxtHooks {
    'schema-org:meta': (meta: import('../../node_modules/.pnpm/nuxt-schema-org@5.0.5_@unhead+vue@2.0.10_vue@3.5.17_typescript@5.8.3___magicast@0.3.5_vue@3.5.17_typescript@5.8.3_/node_modules/nuxt-schema-org/dist/runtime/types').MetaInput) => void | Promise<void>
  }
}

export {}
