import { defineEventHandler } from 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/h3@1.15.3/node_modules/h3/dist/index.mjs';
import { f as fontEventHandler } from '../../../_/eventHandlers.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/ufo@1.6.1/node_modules/ufo/dist/index.mjs';
import '../../../nitro/nitro.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/unhead@2.0.10/node_modules/unhead/dist/index.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/destr@2.0.5/node_modules/destr/dist/index.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/hookable@5.5.3/node_modules/hookable/dist/index.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/ofetch@1.4.1/node_modules/ofetch/dist/node.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/node-mock-http@1.0.0/node_modules/node-mock-http/dist/index.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/unstorage@1.16.0_db0@0.3.2_better-sqlite3@11.10.0__ioredis@5.6.1/node_modules/unstorage/dist/index.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/unstorage@1.16.0_db0@0.3.2_better-sqlite3@11.10.0__ioredis@5.6.1/node_modules/unstorage/drivers/fs.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/unstorage@1.16.0_db0@0.3.2_better-sqlite3@11.10.0__ioredis@5.6.1/node_modules/unstorage/drivers/fs-lite.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/unstorage@1.16.0_db0@0.3.2_better-sqlite3@11.10.0__ioredis@5.6.1/node_modules/unstorage/drivers/lru-cache.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/ohash@2.0.11/node_modules/ohash/dist/index.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/klona@2.0.6/node_modules/klona/dist/index.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/defu@6.1.4/node_modules/defu/dist/defu.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/scule@1.3.0/node_modules/scule/dist/index.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/unctx@2.4.1/node_modules/unctx/dist/index.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/radix3@1.1.2/node_modules/radix3/dist/index.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/vue@3.5.17_typescript@5.8.3/node_modules/vue/index.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/consola@3.4.2/node_modules/consola/dist/index.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/@unocss+core@66.2.3/node_modules/@unocss/core/dist/index.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/@unocss+preset-wind3@66.2.3/node_modules/@unocss/preset-wind3/dist/index.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/devalue@5.1.1/node_modules/devalue/index.js';
import 'node:fs';
import 'node:url';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/pathe@2.0.3/node_modules/pathe/dist/index.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/@iconify+utils@2.3.0/node_modules/@iconify/utils/lib/index.mjs';
import 'node:module';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/unhead@2.0.10/node_modules/unhead/dist/server.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/unhead@2.0.10/node_modules/unhead/dist/plugins.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/vue-bundle-renderer@2.1.1/node_modules/vue-bundle-renderer/dist/runtime.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/vue@3.5.17_typescript@5.8.3/node_modules/vue/server-renderer/index.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/unhead@2.0.10/node_modules/unhead/dist/utils.mjs';
import 'file:///Users/devin/repos/projects/nuxt-astronaut-theme/node_modules/.pnpm/db0@0.3.2_better-sqlite3@11.10.0/node_modules/db0/dist/connectors/better-sqlite3.mjs';
import '../../../_/emojis.mjs';

const font = defineEventHandler(fontEventHandler);

export { font as default };
//# sourceMappingURL=font.mjs.map
