import type { PageCollectionItemBase, DataCollectionItemBase } from '@nuxt/content'

declare module '@nuxt/content' {
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface ShopCollectionItem extends PageCollectionItemBase {
    title: string;
    slug?: string;
    excerpt?: string;
    publishDate?: string;
    image?: string;
    category?: string;
  }
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface LegalCollectionItem extends PageCollectionItemBase {
    title: string;
    excerpt?: string;
    publishDate?: string;
  }
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface PagesCollectionItem extends PageCollectionItemBase {
    title: string;
    excerpt?: string;
    publishDate?: string;
  }
  

  interface PageCollections {
    shop: ShopCollectionItem
    legal: LegalCollectionItem
    pages: PagesCollectionItem
  }

  interface Collections {
    shop: ShopCollectionItem
    legal: LegalCollectionItem
    pages: PagesCollectionItem
  }
}
